name: Checkers

on:
  pull_request:
  push:
  schedule:
  - cron: '30 12 * * *'
  workflow_dispatch:

jobs:

  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: JustinBeckwith/linkinator-action@v1.10.4
      with:
        paths: '*.md'

  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: tbroadley/spellchecker-cli-action@v1.1.1
      with:
        dictionaries: '.github/dictionary.txt'
        files: '*.md'
