name: Test markdownlint-cli2-action

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test-script:
    name: Run test script
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
    - run: npm install
    - run: npm run test
  no-globs:
    name: No globs (README.md, 0 errors)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
  one-glob-file:
    name: One glob (test/errors.md, 3 errors)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        globs: test/errors.md
      continue-on-error: true
      id: test
    - run: exit 1
      if: steps.test.outcome != 'failure'
  one-glob-pattern:
    name: One glob (README.md, 0 errors)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        globs: '*.md'
  two-globs:
    name: Two globs (README.md and test/errors.md, 3 errors)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        globs: |
          *.md
          test/*
      continue-on-error: true
      id: test
    - run: exit 1
      if: steps.test.outcome != 'failure'
  separator:
    name: Separator (README.md and test/errors.md, 3 errors)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        globs: '*.md,test/*'
        separator: ','
      continue-on-error: true
      id: test
    - run: exit 1
      if: steps.test.outcome != 'failure'
  command-config:
    name: Command = config (test/errors.md, 2 errors)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rm .markdownlint.json
    - uses: ./
      with:
        command: config
        globs: |
          config/test.markdownlint.jsonc
          test/*
      continue-on-error: true
      id: test
    - run: exit 1
      if: steps.test.outcome != 'failure'
  command-config-invalid:
    name: Command = config (invalid configuration file, fails)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        command: config
        globs: |
          invalid.markdownlint.jsonc
          test/*
      continue-on-error: true
      id: test
    - run: exit 1
      if: steps.test.outcome != 'failure'
  command-config-missing:
    name: Command = config (missing configuration file, fails)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        command: config
      continue-on-error: true
      id: test
    - run: exit 1
      if: steps.test.outcome != 'failure'
  command-fix:
    name: Command = fix (test/errors.md, 0 errors)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        command: fix
        globs: 'test/*'
  command-unsupported:
    name: Command = unsupported (fails)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        command: unsupported
      continue-on-error: true
      id: test
    - run: exit 1
      if: steps.test.outcome != 'failure'
  config:
    name: config (test/errors.md, 2 errors)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rm .markdownlint.json
    - uses: ./
      with:
        config: 'config/test.markdownlint.jsonc'
        globs: 'test/*'
      continue-on-error: true
      id: test
    - run: exit 1
      if: steps.test.outcome != 'failure'
  config-invalid:
    name: config (invalid configuration file, fails)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        config: 'invalid.markdownlint.jsonc'
        globs: 'test/*'
      continue-on-error: true
      id: test
    - run: exit 1
      if: steps.test.outcome != 'failure'
  fix:
    name: fix (test/errors.md, 0 errors)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        fix: true
        globs: 'test/*'
